name: main

on:
  push:
    branches:
      - master

jobs:
  lint:
    name: "Ruff"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv sync --locked --all-extras --dev
      - uses: astral-sh/ruff-action@v3
        with:
          src: >-
            ./api
            ./tests
      - run: ruff format
      - run: ruff check

  test:
    name: "Pytest"
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv sync --locked --all-extras --dev
      - run: uv run pytest tests

  release:
    name: "Bump Version"
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install python-semantic-release
        run: pip install python-semantic-release

      - name: Generate Version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: get_version
        run: |
          semantic-release version --skip-build --prerelease --no-changelog  --no-vcs-release
          echo "version=$(semantic-release version --print-last-released)" >> "$GITHUB_OUTPUT"

  docker:
    name: "Create image"
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: sehat1137/github-actions-in-action:${{ needs.release.outputs.version }}
