name: main

on:
  push:
    branches:
      - master

jobs:
  lint:
    name: "Ruff"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv sync --locked --all-extras --dev
      - uses: astral-sh/ruff-action@v3
        with:
          src: >-
            ./api
            ./tests
      - run: ruff format
      - run: ruff check

  test:
    name: "Pytest"
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv sync --locked --all-extras --dev
      - run: uv run pytest tests

  version:
    name: "Version"
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-tag.outputs.image-tag }}
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install python-semantic-release
        run: pip install python-semantic-release
      - name: Generate Version
        id: get-tag
        run: |
          echo "image-tag=$(semantic-release version --print-last-released)+${{github.run_id}}" >> "$GITHUB_OUTPUT"
          echo "$(semantic-release version --print-last-released)+${{github.run_id}}"

  build-image:
    name: "Build Docker image"
    runs-on: ubuntu-latest
    needs: [version]
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        id: build
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: sehat1137/github-actions-in-action:${{ needs.version.outputs.image-tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  check-image:
    name: "Check image vulnerabilities"
    runs-on: ubuntu-latest
    needs: [build-image]
    steps:
      - name: Inspect image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: sehat1137/github-actions-in-action:${{ needs.version.outputs.image-tag }}
          scan-type: "image"
          output: trivy-report.json
          format: json
          exit-code: 0

      - name: Upload Vulnerability Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json
          retention-days: 30

      - name: Fail build on High/Critical Vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: sehat1137/github-actions-in-action:${{ needs.version.outputs.image-tag }}
          scan-type: "image"
          format: table
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 1
          skip-setup-trivy: true

  push-image:
    name: "Push Docker image"
    runs-on: ubuntu-latest
    needs: [check-image]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: sehat1137/github-actions-in-action:${{ needs.version.outputs.image-tag }}
          cache-from: type=gha
