name: main

on:
  push:
    branches:
      - master

env:
  IMAGE_REPOSITORY: sehat1137/github-actions-in-action

jobs:
  version:
    name: "Set version"
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install python-semantic-release
        run: pip install python-semantic-release
      - name: Generate version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: set-version
        run: |
          VERSION=$(semantic-release version --skip-build --print)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
  image:
    name: "Push to Docker Hub"
    needs: [version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set image
        id: set-image
        run: echo "image=$IMAGE_REPOSITORY:${{ needs.version.outputs.version }}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.set-image.outputs.image }}
